name=input("Enter a name: ")

noun = input("Enter a noun in singular form: ")
adjective_2 = input("Enter an adjective: ")
verb = input("Enter a verb: ")
object = input("Enter an object: ")
verb_2 = input("Enter a verb in present tense: ")
verb_3 = input("Enter a verb past tense: ")
animal = input("Enter an animal: ")
print (      )
print(name + " is ugly ")
print(name + " wants to rub " + food + " all over his face  ")
print ("before he "+ verb_3)
print (" The next day..... " + name + " is bullied at school ")
print ("He gets called a " + noun)
print (name + " decides to "+ verb_2)
print (name + " gets home to discover that his buddies brought him a "+ animal)
